package io.legado.app.constant

@Suppress("ConstPropertyName")
object PreferKey {
    const val language = "language"
    const val fontScale = "fontScale"
    const val themeMode = "themeMode"
    const val userAgent = "userAgent"
    const val customHosts = "customHosts"
    const val videoSetting = "videoSetting"
    const val editTheme = "editTheme"
    const val editThemeDark = "editThemeDark"
    const val editTemeAuto = "editTemeAuto"
    const val showUnread = "showUnread"
    const val showBooknameLayout = "showBooknameLayout"
    const val bookshelfMargin = "bookshelfMargin"
    const val bookGroupStyle = "bookGroupStyle"
    const val useDefaultCover = "useDefaultCover"
    const val loadCoverOnlyWifi = "loadCoverOnlyWifi"
    const val coverShowName = "coverShowName"
    const val coverShowAuthor = "coverShowAuthor"
    const val coverShowNameN = "coverShowNameN"
    const val coverShowAuthorN = "coverShowAuthorN"
    const val remoteServerId = "remoteServerId"
    const val hideStatusBar = "hideStatusBar"
    const val clickActionTL = "clickActionTopLeft"
    const val clickActionTC = "clickActionTopCenter"
    const val clickActionTR = "clickActionTopRight"
    const val clickActionML = "clickActionMiddleLeft"
    const val clickActionMC = "clickActionMiddleCenter"
    const val clickActionMR = "clickActionMiddleRight"
    const val clickActionBL = "clickActionBottomLeft"
    const val clickActionBC = "clickActionBottomCenter"
    const val clickActionBR = "clickActionBottomRight"
    const val hideNavigationBar = "hideNavigationBar"
    const val precisionSearch = "precisionSearch"
    const val readAloudByPage = "readAloudByPage"
    const val ttsEngine = "appTtsEngine"
    const val ttsFollowSys = "ttsFollowSys"
    const val ttsSpeechRate = "ttsSpeechRate"
    const val ttsCacheEnabled = "ttsCacheEnabled"
    const val sysTtsPackageName = "sysTtsPackageName"
    const val sysTtsSynthesizeTimeout = "sysTtsSynthesizeTimeout"
    const val ttsRetryCount = "ttsRetryCount"
    const val ttsRetrySkipOnFail = "ttsRetrySkipOnFail"
    /** 实时更新音频开关：开启后检测到 gengxin.json 信号时停止朗读、删除所有缓存、重新开始 */
    const val gengxinRealtimeUpdate = "gengxinRealtimeUpdate"
    const val prevKeys = "prevKeyCodes"
    const val nextKeys = "nextKeyCodes"
    const val showDiscovery = "showDiscovery"
    const val enableReview = "enableReview"
    const val showRss = "showRss"
    const val bookshelfLayout = "bookshelfLayout"
    const val bookshelfSort = "bookshelfSort"
    const val bookExportFileName = "bookExportFileName"
    const val bookImportFileName = "bookImportFileName"
    const val episodeExportFileName = "episodeExportFileName"
    const val recordLog = "recordLog"
    const val processText = "process_text"
    const val cleanCache = "cleanCache"
    const val saveTabPosition = "saveTabPosition"
    const val fontFolder = "fontFolder"
    const val backupPath = "backupUri"
    const val restoreIgnore = "restoreIgnore"
    const val threadCount = "threadCount"
    const val webPort = "webPort"
    const val keepLight = "keep_light"
    const val webService = "webService"
    const val webDavUrl = "web_dav_url"
    const val webDavAccount = "web_dav_account"
    const val webDavPassword = "web_dav_password"
    const val webDavDir = "webDavDir"
    const val enableCustomExport = "enableCustomExport"
    const val exportToWebDav = "webDavCacheBackup"
    const val exportNoChapterName = "exportNoChapterName"
    const val exportType = "exportType"
    const val exportPictureFile = "exportPictureFile"
    const val changeSourceCheckAuthor = "changeSourceCheckAuthor"
    const val changeSourceLoadToc = "changeSourceLoadToc"
    const val changeSourceLoadInfo = "changeSourceLoadInfo"
    const val changeSourceLoadWordCount = "changeSourceLoadWordCount"
    const val chineseConverterType = "chineseConverterType"
    const val launcherIcon = "launcherIcon"
    const val textSelectAble = "selectText"
    const val shareLayout = "shareLayout"
    const val comicStyleSelect = "comicStyleSelect"
    const val readStyleSelect = "readStyleSelect"
    const val systemTypefaces = "system_typefaces"
    const val readBodyToLh = "readBodyToLh"
    const val textFullJustify = "textFullJustify"
    const val textBottomJustify = "textBottomJustify"
    const val adaptSpecialStyle = "adaptSpecialStyle"
    const val autoReadSpeed = "autoReadSpeed"
    const val barElevation = "barElevation"
    const val transparentStatusBar = "transparentStatusBar"
    const val immNavigationBar = "immNavigationBar"
    const val defaultCover = "defaultCover"
    const val defaultCoverDark = "defaultCoverDark"
    const val replaceEnableDefault = "replaceEnableDefault"
    const val showBrightnessView = "showBrightnessView"
    const val autoClearExpired = "autoClearExpired"
    const val autoChangeSource = "autoChangeSource"
    const val importKeepName = "importKeepName"
    const val importKeepGroup = "importKeepGroup"
    const val screenOrientation = "screenOrientation"
    const val syncBookProgress = "syncBookProgress"
    const val syncBookProgressPlus = "syncBookProgressPlus"
    const val cronet = "Cronet"
    const val antiAlias = "antiAlias"
    const val bitmapCacheSize = "bitmapCacheSize"
    const val imageRetainNum = "imageRetainNum"
    const val preDownloadNum = "preDownloadNum"
    const val mangaPreDownloadNum = "mangaPreDownloadNum"
    const val mangaAutoPageSpeed = "mangaAutoPageSpeed"
    const val mangaFooterConfig = "mangaFooterConfig"
    const val disableClickScroll = "disableClickScroll"
    const val enableMangaHorizontalScroll = "enableMangaHorizontalScroll"
    const val hideMangaTitle = "hideMangaTitle"
    const val mangaColorFilter = "mangaColorFilter"
    const val enableMangaEInk = "enableMangaEInk"
    const val mangaEInkThreshold = "mangaEInkThreshold"
    const val disableHorizontalPageSnap = "disableHorizontalPageSnap"
    const val enableMangaGray = "enableMangaGray"
    const val autoRefresh = "auto_refresh"
    const val onlyUpdateRead = "onlyUpdateRead"
    const val defaultToRead = "defaultToRead"
    const val exportCharset = "exportCharset"
    const val exportUseReplace = "exportUseReplace"
    const val useZhLayout = "useZhLayout"
    const val brightness = "brightness"
    const val nightBrightness = "nightBrightness"
    const val expandTextMenu = "expandTextMenu"
    const val doublePageHorizontal = "doubleHorizontalPage"
    const val readUrlOpenInBrowser = "readUrlInBrowser"
    const val defaultBookTreeUri = "defaultBookTreeUri"
    const val checkSource = "checkSource"
    const val uploadRule = "uploadRule"
    const val tocUiUseReplace = "tocUiUseReplace"
    const val tocCountWords = "tocCountWords"
    const val enableReadRecord = "enableReadRecord"
    const val localBookImportSort = "localBookImportSort"
    const val customWelcome = "customWelcome"
    const val welcomeShowTime = "welcomeShowTime"
    const val welcomeImage = "welcomeImagePath"
    const val welcomeImageDark = "welcomeImagePathDark"
    const val welcomeShowText = "welcomeShowText"
    const val welcomeShowTextDark = "welcomeShowTextDark"
    const val welcomeShowIcon = "welcomeShowIcon"
    const val welcomeShowIconDark = "welcomeShowIconDark"
    const val pageTouchSlop = "pageTouchSlop"
    const val pageTouchClick = "pageTouchClick"
    const val showAddToShelfAlert = "showAddToShelfAlert"
    const val ignoreAudioFocus = "ignoreAudioFocus"
    const val parallelExportBook = "parallelExportBook"
    const val exportAddAnnotation = "exportAddAnnotation"
    const val progressBarBehavior = "progressBarBehavior"
    const val sourceEditMaxLine = "sourceEditMaxLine"
    const val ttsTimer = "ttsTimer"
    const val noAnimScrollPage = "noAnimScrollPage"
    const val webDavDeviceName = "webDavDeviceName"
    const val webServiceWakeLock = "webServiceWakeLock"
    const val audioPlayWakeLock = "audioPlayWakeLock"
    const val readAloudWakeLock = "readAloudWakeLock"
    const val showLastUpdateTime = "showLastUpdateTime"
    const val showWaitUpCount = "showWaitUpCount"
    const val clearWebViewData = "clearWebViewData"
    const val onlyLatestBackup = "onlyLatestBackup"
    const val brightnessVwPos = "brightnessVwPos"
    const val shrinkDatabase = "shrinkDatabase"
    const val batchChangeSourceDelay = "batchChangeSourceDelay"
    const val openBookInfoByClickTitle = "openBookInfoByClickTitle"
    const val defaultHomePage = "defaultHomePage"
    const val showBookshelfFastScroller = "showBookshelfFastScroller"
    const val importKeepEnable = "importKeepEnable"
    const val importShowComment = "importShowComment"
    const val previewImageByClick = "previewImageByClick"
    const val clickImgWay = "clickImgWay"
    const val keyPageOnLongPress = "keyPageOnLongPress"
    const val volumeKeyPage = "volumeKeyPage"
    const val volumeKeyPageOnPlay = "volumeKeyPageOnPlay"
    const val mouseWheelPage = "mouseWheelPage"
    const val recordHeapDump = "recordHeapDump"
    const val optimizeRender = "optimizeRender"
    const val updateToVariant = "updateToVariant"
    const val streamReadAloudAudio = "streamReadAloudAudio"
    const val pauseReadAloudWhilePhoneCalls = "pauseReadAloudWhilePhoneCalls"
    const val readAloudByMediaButton = "readAloudByMediaButton"
    const val showMangaUi = "showMangaUi"
    const val disableMangaScale = "disableMangaScale"
    const val disableMangaPageAnim = "disableMangaPageAnim"
    const val paddingDisplayCutouts = "paddingDisplayCutouts"
    const val autoCheckNewBackup = "autoCheckNewBackup"

    const val dThemeName = "durThemeName"
    const val dNThemeName = "durThemeNameNight"

    const val cPrimary = "colorPrimary"
    const val cAccent = "colorAccent"
    const val cBackground = "colorBackground"
    const val cBBackground = "colorBottomBackground"
    const val bgImage = "backgroundImage"
    const val bgImageBlurring = "backgroundImageBlurring"
    const val tNavBar = "transparentNavBar"

    const val cNPrimary = "colorPrimaryNight"
    const val cNAccent = "colorAccentNight"
    const val cNBackground = "colorBackgroundNight"
    const val cNBBackground = "colorBottomBackgroundNight"
    const val bgImageN = "backgroundImageNight"
    const val bgImageNBlurring = "backgroundImageNightBlurring"
    const val tNavBarN = "transparentNavBarNight"

    const val showReadTitleAddition = "showReadTitleAddition"
    const val readBarStyleFollowPage = "readBarStyleFollowPage"
    const val contentSelectSpeakMod = "contentReadAloudMod"
    const val editFontScale = "editFontScale"
    const val editNonPrintable = "editNonPrintable"
    const val editAutoWrap = "editAutoWrap"
    const val editAutoComplete = "editAutoComplete"
    const val showBoardLine = "showBoardLine"

    // --- 背景音乐 (BGM) 与 标题朗读 相关新增 ---
    const val bgmEnabled = "bgmEnabled"
    const val bgmPath = "bgmPath"
    const val bgmVolume = "bgmVolume"
    const val bgmAIEnabled = "bgmAIEnabled"
    const val bgmAICharInterval = "bgmAICharInterval"
    const val soundEffectMode = "soundEffectMode"
    // 当前书籍音效模式：key = bookSoundEffectMode_${bookUrl}，value = follow/off/normal/all
    const val bookSoundEffectModePrefix = "bookSoundEffectMode_"
    const val soundEffectOffsetChars = "soundEffectOffsetChars"
    const val soundEffectVolume = "soundEffectVolume"
    const val mixSoundEffectOnMerge = "mixSoundEffectOnMerge"
    const val readAloudTitle = "readAloudTitle"
    const val readAloudStartFromFirst = "readAloudStartFromFirst"
    const val autoMergeAudioOnChapterEnd = "autoMergeAudioOnChapterEnd"
    const val convertToMp3AfterMerge = "convertToMp3AfterMerge"
    const val saveTextWithMerge = "saveTextWithMerge"
    const val saveVideoWithMerge = "saveVideoWithMerge"
    const val shortAudioMinDuration = "shortAudioMinDuration"
    const val srtSubtitleMaxChars = "srtSubtitleMaxChars"
    const val srtSubtitleTimeOffset = "srtSubtitleTimeOffset"
    const val srtSilenceMatchRange = "srtSilenceMatchRange"
    const val showReadAloudCoverSubtitle = "showReadAloudCoverSubtitle"
    // 朗读界面是否隐藏当前章节进度条，默认 true 隐藏（开启即去掉进度条）
    const val readAloudHideChapterProgress = "readAloudHideChapterProgress"
    // 朗读界面小图（封面/本地图）与顶部的距离，单位 dp，默认 16
    const val readAloudCoverTopMargin = "readAloudCoverTopMargin"

    // 保存为视频时的字幕样式设置
    const val videoSubtitleFontSizeScale = "videoSubtitleFontSizeScale" // 字号相对默认比例，1.0=默认
    const val videoSubtitleVOffset = "videoSubtitleVOffset"             // 字幕垂直偏移(画面高度比例)，正=上移，负=下移
    const val videoSubtitleSplit = "videoSubtitleSplit"               // 是否按句(标点)切割字幕，默认 false
    const val videoSubtitleFontColor = "videoSubtitleFontColor"        // 字幕填充色(十六进制，如 #FF000000)
    const val videoSubtitleStrokeWidth = "videoSubtitleStrokeWidth"    // 描边粗细(相对字号比例，默认 0.12)
    const val videoSubtitleStrokeColor = "videoSubtitleStrokeColor"    // 描边颜色(十六进制，如 #FFFFFFFF)
    const val videoSubtitleStyle = "videoSubtitleStyle"            // 视频字幕样式（字号/字色/描边粗细/描边色）汇总设置
    const val readAloudCoverWidth = "readAloudCoverWidth"
    const val readAloudBackToBackground = "readAloudBackToBackground"
    const val readAloudFloatWindow = "readAloudFloatWindow"
    const val readAloudFloatClickSwap = "readAloudFloatClickSwap"
    const val readAloudFloatX = "readAloudFloatX"
    const val readAloudFloatY = "readAloudFloatY"
    const val readAloudFloatEdgeOffset = "readAloudFloatEdgeOffset"
    const val videoFloatX = "videoFloatX"
    const val videoFloatY = "videoFloatY"

    // 系统TTS当前使用的voice名称（用于缓存文件名匹配）
    const val sysTtsVoiceName = "sysTtsVoiceName"

    // 朗读封面跑马灯边框
    const val readAloudCoverMarqueeEnabled = "readAloudCoverMarqueeEnabled"
    const val readAloudCoverMarqueeSpeed = "readAloudCoverMarqueeSpeed"
    const val marqueeBgmLinkEnabled = "marqueeBgmLinkEnabled"

    // 角色标注显示开关与偏移量
    const val showRoleAnnotation = "showRoleAnnotation"
    const val roleAnnotationOffset = "roleAnnotationOffset"

    // 音频缓存标记显示开关
    const val showAudioCacheIndicator = "showAudioCacheIndicator"

    // 朗读缓存音频统一转换为 WAV (24000Hz, 16bit, 单声道)
    const val convertCacheToWav = "convertCacheToWav"

    // 转换为 WAV 时的音量增益倍数（默认 1.0，最大 3.0，超过自动截断为 3.0）
    const val convertCacheToWavGain = "convertCacheToWavGain"

    // 朗读播放时的音量增益倍数（默认 1.0，范围 0.5~5.0，超过自动截断为 5.0）
    const val readAloudVolumeGain = "readAloudVolumeGain"

    // --- AI 生图配置 ---
    const val readAloudAiImage = "readAloudAiImage"
    // 启用AI生图（每本书单独设置），key = aiImageEnablePrefix_${bookUrl}
    const val aiImageEnablePrefix = "aiImageEnable_"
    // AI 生图临时缓存保留数量上限（默认 50）
    const val aiImageCacheCount = "aiImageCacheCount"
    const val aiImageSize = "aiImageSize"
    // 朗读/大图图片轮播间隔（秒），0=不自动轮播，仅手动切换
    const val readAloudImageInterval = "readAloudImageInterval"
    // 书籍与模板的绑定关系：key = aiImageTemplateBind_${bookUrl}，value = templateId
    const val aiImageTemplateBindPrefix = "aiImageTemplateBind_"
    // 上次编辑的模板 id（记住用户上次编辑哪个模板，下次打开设置时恢复）
    const val aiImageLastEditTemplateId = "aiImageLastEditTemplateId"
    // AI 生图分析字数（每读多少字触发一次，默认200）
    const val aiImageCharCount = "aiImageCharCount"
    // AI 生图上下文字数（正文前/后的上文与后续字数，默认50）
    const val aiImageContextCharCount = "aiImageContextCharCount"
    // AI 生图重试次数（生图失败后重试次数，默认1）
    const val aiImageRetryCount = "aiImageRetryCount"
    // AI 生图请求间隔时间（秒，每次请求与重试前等待，避免触发 API 频率限制，默认1.0）
    const val aiImageRequestInterval = "aiImageRequestInterval"
    // 是否保存AI生图到持久目录（每本书单独设置），key = aiImageSavePrefix_${bookUrl}
    const val aiImageSavePrefix = "aiImageSave_"
}
